apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  username: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  rootPassword: {{ .Values.database.rootPassword | b64enc }}
