replicaCount: 2

image:
  repository: your-dockerhub-user/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: DATABASE_URL
    value: "jdbc:mysql://database.default.svc.cluster.local:3306/mydb"
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: database-credentials
        key: username
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: database-credentials
        key: password
